# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d9ab78e8a92564567a455384e51050f0e9d684e30cea5717dd5536fb2eda70b982dcd793903b8f14b26256d9b6ddb9f91855ae60ddd1a4788d4788b37efea45
  consumer_key: 23d5248f57eb7673f0d746ca74178468
  consumer_secret: a4e44c722671654336607b627e6a3e56
test:
  secret_key_base: 3cc6948aba000b1633459546cfe288b2ab5f72741e53a3c0550d5d58eceaf62a9ddb4a0df4f00fa69d2d8997bb5eb64923790e7cfed1c4f34d5208f70ee47ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
